### ISSUE TITLE
MAX_ITERATIONS is required?

### ISSUE THREAD

**Issue by hfsugar** [Draxent/ConnectedComponents#1]
My input data needs more than 30 iterations, so that I changed MAX_ITERATIONS from 30 to 100. However, the checkok is false. Why it failed? I'm wondering if MAX_ITERATIONS is required and what is the maxmium of MAX_ITERATIONS. Thanks!

**Comment by hfsugar** [comment]
By the way, I changed IntWritable to LongWritable because the numbers of input data over limitation of Integer.

**Comment by Draxent** [comment]
Hi hfsugar,
unfortunately, I wrote the code more than 3 years ago and I do not recall a lot.

I checked the code and I do not see any reason why this should fail.
I think I used MAX_ITERATIONS only to limit the number of iterations
if the graph was not converging soon, in order to limit the resource consumption.

**Comment by hfsugar** [comment]
Got it. I have fixed. It works very well! Thank you very much!
